{
    "openapi": "3.0.0",
    "info": {
        "title": "Solid Introduction Documentation",
        "description": "API to manage a users",
        "version": "1.0.0",
        "contact": {
            "email": "fernandobrino11@gmail.com"
        }
    },
    "servers": [
        {
            "url": "http://localhost:3333",
            "description": "Test server"
        }
    ],
    "paths": {
        "/users": {
            "post": {
                "tags": ["User"],
                "summary": "Create a new user",
                "description": "This route will create a new user",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/User"
                            },
                            "example": {
                                "name": "Fernando Brino",
                                "email": "fernandobrino11@gmail.com"
                            }
                            
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Created Successfully",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/User"
                                },
                                "example": {
                                    "id": "a7320e40-eab3-4a00-aad7-63f9876bec0b",
                                    "admin": false,
                                    "name": "Olivia Rodrigo",
                                    "email": "olivia11@gmail.com",
                                    "created_at": "2022-05-17T00:45:57.336Z",
                                    "updated_at": "2022-05-17T00:46:05.997Z"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "User with this email already exists",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "example": {
                                        "error": "Um usuário com esse email já existe"
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "get": {
                "tags": ["User"],
                "summary": "List all users",
                "description": "List all users",
                "parameters": [
                    {
                        "user_id": "user_id",
                        "in": "headers",
                        "description": "Id do usuário para listar todos usuários",
                        "required": "true"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/components/schemas/User"
                                    }
                                },
                                "example": {
                                    "id": "a7320e40-eab3-4a00-aad7-63f9876bec0b",
                                    "admin": true,
                                    "name": "Olivia Rodrigo",
                                    "email": "olivia11@gmail.com",
                                    "created_at": "2022-05-17T00:45:57.336Z",
                                    "updated_at": "2022-05-17T00:46:05.997Z"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Just admin's can list users",
                        "content": {
                            "schema": {
                                "example": {
                                    "error": "Apenas admin's podem listar usuários"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/users/{user_id}": {
            "get": {
                "tags": ["User"],
                "summary": "Show user by id",
                "description": "Show a user by id",
                "parameters": [
                    {
                        "user_id": "user_id",
                        "in": "path",
                        "description": "Busca pelo id do usuário",
                        "required": "true"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/User"
                                },
                                "example": {
                                    "id": "a7320e40-eab3-4a00-aad7-63f9876bec0b",
                                    "admin": true,
                                    "name": "Olivia Rodrigo",
                                    "email": "olivia11@gmail.com",
                                    "created_at": "2022-05-17T00:45:57.336Z",
                                    "updated_at": "2022-05-17T00:46:05.997Z"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "content": {
                            "schema": {
                                "example": {
                                    "error": "Usuário não encontrado"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/users/{user_id}/admin": {
            "patch": {
                "tags": ["User"],
                "summary": "Turn an user as admin",
                "description": "Turn an user as admin",
                "parameters": [
                    {
                        "user_id": "user_id",
                        "in": "path",
                        "description": "Tornar um usuário admin pelo id",
                        "required": "true"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/User"
                                },
                                "example": {
                                    "id": "a7320e40-eab3-4a00-aad7-63f9876bec0b",
                                    "admin": true,
                                    "name": "Olivia Rodrigo",
                                    "email": "olivia11@gmail.com",
                                    "created_at": "2022-05-17T00:45:57.336Z",
                                    "updated_at": "2022-05-17T00:46:05.997Z"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "content": {
                            "schema": {
                                "example": {
                                    "error": "Usuário não encontrado"
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "components": {
        "schemas": {
            "User": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "string"
                    },
                    "admin": {
                        "type": "boolean"
                    },
                    "name": {
                        "type": "string"
                    },
                    "email": {
                        "type": "string"
                    },
                    "created_at": {
                        "type": "string"
                    },
                    "updated_at": {
                        "type": "string"
                    }
                }
            }
        }
    }
}